//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ListNo { get; set; }
        public string ListName { get; set; }
        public string ListDesc { get; set; }
        public System.DateTime ListDate { get; set; }
        public string ListUser { get; set; }
    }
}
